In [1]:
!pip install numpy

In [2]:
#import the numpy package under the name as np
import numpy as np

In [3]:
#python array
arr=np.array([[1,2,3],
              [4,2,5]])

In [4]:
#type of array
type(arr)

numpy.ndarray

In [5]:
#dimension of array
arr.ndim

2

In [6]:
#No.of rows and columns
arr.shape

(2, 3)

In [7]:
arr=np.array([1,2,3])
arr.shape #It is a 1D array with 3 elements in it

(3,)

In [8]:
arr.size #total number of elements present in an array

3

In [9]:
arr.dtype #type of element in an array

dtype('int32')

In [10]:
#Create a null vector of size 10
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
#to find the memory size of any array
Z = np.zeros((9,8))
print("%d bytes" % (Z.size * Z.itemsize))

576 bytes


In [12]:
#Create a null vector of size 10 but the fifth value which is 1
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
#Create a vector with values ranging from 10 to 49
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [14]:
#Reverse a vector (first element becomes last)
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [15]:
#Create a 3x3 matrix with values ranging from 0 to 8 
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
#Find indices of non-zero elements from \[1,2,0,0,4,0\]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [17]:
#Create a 3x3 identity matrix
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
#Create a 3x3x3 array with random values
Z = np.random.random((3,3,3))
print(Z)

[[[0.48785353 0.96133035 0.78203263]
  [0.82518743 0.65244897 0.74586776]
  [0.39305201 0.95441412 0.87998679]]

 [[0.29213482 0.60627813 0.63291782]
  [0.99593059 0.4317654  0.62397848]
  [0.67646098 0.65057239 0.01929787]]

 [[0.981016   0.69295073 0.75538994]
  [0.8984965  0.84899424 0.53686554]
  [0.34099536 0.54659708 0.31762751]]]


In [19]:
#Create a 10x10 array with random values and find the minimum and maximum values
Z=np.random.random((10,10))
minimum=z.min()
maximum=z.max()
print("The min value is",minimum)
print("The max value is",maximum)

The min value is 0
The max value is 8


In [20]:
#Create a random vector of size 30 and find the mean value
Z=np.random.random((30))
m=z.mean()
print(m)

4.0


In [21]:
#Create a 2d array with 1 on the border and 0 inside
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
